# Performance in each attribute is determined by a Gaussian distribution with mean = pet's attribute value,
# sigma = variance
all:
  variance: 8

# Scores for a contest are determined by multiplying scores for each attribute by the constants below and adding results
contests:

  power:
    strength: 3
    agility: 1

  evasion:
    agility: 1
    wit: 3
    perception: 2

  speed:
    agility: 3
    perception: 1
